Search
kosovych/rn-tmdb pull request #2
Opened 2021-09-30 17:05 UTC by kosovych

2021-09-30 17:40 UTC, TretyakovDV commented
Do you try use react and  redux devtools in project?

2021-09-30 17:41 UTC, TretyakovDV commented on jsconfig.json
> +    "paths": {
👍

2021-09-30 17:48 UTC, dymytrii-tretiakov requested changes

2021-09-30 17:48 UTC, TretyakovDV commented on src/components/shared/Empty/index.js
> +        source={require('../../../../public/images/empty.png')}
may you add short path to the image folder?

2021-09-30 17:48 UTC, dymytrii-tretiakov commented on src/schemas/searchMoviesSchema.js
> +import {schema} from 'normalizr';
do you know why need a `normalizr` ?

2021-09-30 17:48 UTC, dymytrii-tretiakov commented on src/components/shared/SearchInput/index.js
> +    borderColor: '#dd1f00',
maybe create theme file in constants and move all hex to them?

2021-10-01 11:44 UTC, kosovych commented on src/schemas/searchMoviesSchema.js
> +import {schema} from 'normalizr';
yes

2021-10-01 12:38 UTC, merged